java_library(
    name = "liftwizard-config-logging-logstash-console",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-logging/liftwizard-config-logging-logstash-encoder",
        "@maven//:ch_qos_logback_logback_access",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:ch_qos_logback_logback_core",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:io_dropwizard_dropwizard_logging",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
