java_library(
    name = "liftwizard-graphql-instrumentation-metrics",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-graphql/liftwizard-graphql-data-fetcher-async",
        "//liftwizard-graphql/liftwizard-graphql-instrumentation",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_graphql_java_graphql_java",
        "@maven//:io_dropwizard_metrics_metrics_annotation",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
