repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
        exclude: ^\.idea/
      - id: trailing-whitespace
        exclude: ^\.idea/
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: local
    hooks:
      - id: oxfmt
        name: vp fmt
        entry: vp fmt --no-error-on-unmatched-pattern
        language: system
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: markdownlint-cli2
        language: system
        types: [markdown]
