[tools]
java = "oracle-17.0.10"
maven = "3.9.9"
mvnd = "1.0.2"
node = "22.13.1"
"npm:markdownlint-cli" = "0.44.0"
"npm:strip-ansi-cli" = "4.0.0"

[alias]
mvnd = "asdf:https://github.com/joschi/asdf-mvnd"
