java_library(
    name = "liftwizard-bundle-logging-uncaught-exception-handler",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-bundle/liftwizard-bundle-prioritized-api",
        "//liftwizard-logging/liftwizard-logging-uncaught-exception-handler",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
