/*
 * Copyright 2026 Craig Motlin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.liftwizard.generator.rewrite;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.eclipse.collections.api.factory.Lists;
import org.eclipse.collections.api.factory.SortedSets;
import org.eclipse.collections.api.list.MutableList;
import org.eclipse.collections.api.map.MutableMap;
import org.eclipse.collections.api.set.MutableSet;
import org.eclipse.collections.impl.map.mutable.MapAdapter;
import org.eclipse.collections.impl.set.mutable.SetAdapter;
import org.openrewrite.config.Environment;
import org.openrewrite.config.OptionDescriptor;
import org.openrewrite.config.RecipeDescriptor;

public class CompositeRecipeGenerator {

	private final String indent;

	public CompositeRecipeGenerator() {
		this("    ");
	}

	public CompositeRecipeGenerator(String indent) {
		this.indent = indent;
	}

	public String generate(Environment env, FilteredRecipeSpec spec) {
		RecipeDescriptor root = this.findDescriptor(env, spec.getBaseRecipeName());

		MutableMap<String, String> exclusionReasons = MapAdapter.adapt(new LinkedHashMap<>());
		for (RecipeExclusion exclusion : spec.getExclusions()) {
			exclusionReasons.put(exclusion.getRecipeName(), exclusion.getReason());
		}

		MutableSet<String> matchedExclusions = SetAdapter.adapt(new LinkedHashSet<>());
		List<Object> filteredEntries = this.filterRecipeList(root.getRecipeList(), exclusionReasons, matchedExclusions);

		Set<String> unmatchedExclusions = SortedSets.mutable.withAll(exclusionReasons.keySet());
		unmatchedExclusions.removeAll(matchedExclusions);
		if (!unmatchedExclusions.isEmpty()) {
			throw new IllegalArgumentException(
				"Exclusions not found in recipe tree of '" + spec.getBaseRecipeName() + "': " + unmatchedExclusions
			);
		}

		return this.renderHeader(spec) + this.renderYaml(spec, filteredEntries);
	}

	private RecipeDescriptor findDescriptor(Environment env, String recipeName) {
		return env
			.listRecipeDescriptors()
			.stream()
			.filter((rd) -> rd.getName().equals(recipeName))
			.findFirst()
			.orElseThrow(() -> new IllegalArgumentException("Recipe not found: " + recipeName));
	}

	private boolean needsExplosion(RecipeDescriptor descriptor, Set<String> exclusions) {
		if (exclusions.contains(descriptor.getName())) {
			return true;
		}
		return descriptor
			.getRecipeList()
			.stream()
			.anyMatch((child) -> this.needsExplosion(child, exclusions));
	}

	private List<Object> filterRecipeList(
		List<RecipeDescriptor> recipeList,
		MutableMap<String, String> exclusionReasons,
		MutableSet<String> matchedExclusions
	) {
		MutableList<Object> result = Lists.mutable.empty();
		for (RecipeDescriptor descriptor : recipeList) {
			if (exclusionReasons.containsKey(descriptor.getName())) {
				matchedExclusions.add(descriptor.getName());
				result.add(new ExcludedRecipe(descriptor.getName(), exclusionReasons.get(descriptor.getName())));
				continue;
			}
			if (!this.needsExplosion(descriptor, exclusionReasons.keySet())) {
				result.add(this.toYamlEntry(descriptor));
			} else {
				result.addAll(this.filterRecipeList(descriptor.getRecipeList(), exclusionReasons, matchedExclusions));
			}
		}
		return result;
	}

	private Object toYamlEntry(RecipeDescriptor descriptor) {
		List<OptionDescriptor> options = descriptor.getOptions();
		MutableMap<String, Object> nonNullOptions = MapAdapter.adapt(new LinkedHashMap<>());
		for (OptionDescriptor option : options) {
			if (option.getValue() != null) {
				nonNullOptions.put(option.getName(), option.getValue());
			}
		}

		if (nonNullOptions.isEmpty()) {
			return descriptor.getName();
		}

		return new ParameterizedEntry(descriptor.getName(), nonNullOptions);
	}

	private String renderHeader(FilteredRecipeSpec spec) {
		// @formatter:off
		//language=yaml
		return ""
				+ "#\n"
				+ "# Generated by CompositeRecipeGenerator. Do not edit manually.\n"
				+ "#\n"
				+ "# Base recipe: " + spec.getBaseRecipeName() + "\n"
				+ "#\n"
				+ "\n";
		// @formatter:on
	}

	private String renderYaml(FilteredRecipeSpec spec, List<Object> entries) {
		// @formatter:off
		//language=yaml
		String header = ""
				+ "---\n"
				+ "type: specs.openrewrite.org/v1beta/recipe\n"
				+ "name: " + spec.getGeneratedRecipeName() + "\n"
				+ "displayName: " + spec.getDisplayName() + "\n"
				+ "description: " + spec.getDescription() + "\n"
				+ "recipeList:\n";
		// @formatter:on

		return header + entries.stream().map(this::renderEntry).collect(Collectors.joining());
	}

	private String renderEntry(Object entry) {
		if (entry instanceof ExcludedRecipe excluded) {
			String comment = excluded.reason() != null && !excluded.reason().isBlank()
				? this.indent + "# " + excluded.reason() + "\n"
				: "";
			return comment + this.indent + "# - " + excluded.recipeName() + "\n";
		} else if (entry instanceof String name) {
			return this.indent + "- " + name + "\n";
		} else if (entry instanceof ParameterizedEntry parameterized) {
			return this.renderMapEntry(parameterized);
		}
		throw new IllegalArgumentException("Unexpected entry type: " + entry.getClass());
	}

	private String renderMapEntry(ParameterizedEntry parameterized) {
		return (
			this.indent
			+ "- "
			+ parameterized.name()
			+ ":\n"
			+ parameterized
				.options()
				.entrySet()
				.stream()
				.map((option) -> this.indent + this.indent + option.getKey() + ": " + option.getValue() + "\n")
				.collect(Collectors.joining())
		);
	}

	private record ExcludedRecipe(String recipeName, String reason) {}

	private record ParameterizedEntry(String name, Map<String, Object> options) {}
}
