java_library(
    name = "liftwizard-graphql-instrumentation-logging",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-graphql/liftwizard-graphql-data-fetcher-async",
        "//liftwizard-graphql/liftwizard-graphql-instrumentation",
        "//liftwizard-logging/liftwizard-logging-mdc-closeable",
        "@maven//:com_graphql_java_graphql_java",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
