java_library(
    name = "liftwizard-bundle-clock",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-clock/liftwizard-config-clock",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_glassfish_hk2_hk2_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
