java_library(
    name = "liftwizard-bundle-logging-config",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-bundle/liftwizard-bundle-prioritized-api",
        "//liftwizard-config/liftwizard-config-enabled",
        "//liftwizard-logging/liftwizard-config-logging-config",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
