java_library(
    name = "liftwizard-servlet-logging",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-servlet/liftwizard-servlet-logging-typesafe",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:javax_servlet_javax_servlet_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_glassfish_jersey_core_jersey_common",
        "@maven//:org_glassfish_jersey_core_jersey_server",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:org_springframework_spring_web",
    ],
)
