java_library(
    name = "liftwizard-config-liquibase-migration",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-config/liftwizard-config-enabled",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:janino_janino",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
