java_library(
    name = "liftwizard-config-connection-manager",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-config/liftwizard-config-data-source",
        "//liftwizard-reladomo/liftwizard-connection-manager",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_db",
        "@maven//:io_dropwizard_dropwizard_validation",
        "@maven//:janino_janino",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
