java_library(
    name = "liftwizard-reladomo-operation-compiler",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-reladomo/liftwizard-reladomo-operation-grammar",
        "@antlr4_runtime//jar",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:janino_janino",
        "@maven//:org_apache_commons_commons_text",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
