java_library(
    name = "liftwizard-servlet-logging-logstash-encoder",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-servlet/liftwizard-servlet-logging-typesafe",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:janino_janino",
        "@maven//:net_logstash_logback_logstash_logback_encoder",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
