java_library(
    name = "liftwizard-config-metrics-reporter-slf4j",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-logging/liftwizard-metrics-reporter-slf4j",
        "@com_google_auto_service",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_metrics",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_hibernate_hibernate_validator",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
