java_library(
    name = "liftwizard-reladomo-test-rule",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-reladomo/liftwizard-connection-manager-h2-memory",
        "//liftwizard-reladomo/liftwizard-ddl-executor",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_goldmansachs_reladomo_reladomo_test_util",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:janino_janino",
        "@maven//:junit_junit",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
