java_library(
    name = "liftwizard-named-data-source-factory",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:io_dropwizard_dropwizard_db",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
