java_library(
    name = "liftwizard-config-clock-incrementing",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-clock/liftwizard-clock-incrementing",
        "//liftwizard-clock/liftwizard-config-clock",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_util",
        "@maven//:io_dropwizard_dropwizard_validation",
        "@maven//:janino_janino",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
