#!/usr/bin/env bash

#MISE description="Run spotless for all formats"

#USAGE flag "--mvn_binary <mvn_binary>"  help="Maven binary to use"
#USAGE flag "--flags <flags>"            help="Additional Maven flags"

set -Eeuo pipefail

mvn_binary="${usage_mvn_binary:-${MVN_BINARY}}"
flags="${usage_flags:-${MVN_FLAGS}}"

# First check for local modifications
mise run git:check-local-modifications

# Clean to avoid issues
mise run maven:clean --mvn_binary "${mvn_binary}" --flags "${flags}"

# Run spotless for all formats
$mvn_binary spotless:apply --projects '!liftwizard-maven-build/liftwizard-minimal-parent,!liftwizard-utility/liftwizard-checkstyle' --activate-profiles spotless-apply,spotless-formats,spotless-java-sort-imports,spotless-java-unused-imports,spotless-java-cleanthat,spotless-sql,spotless-pom,spotless-markdown,spotless-json,spotless-yaml ${flags}

# Check for local modifications again
mise run git:check-local-modifications