java_library(
    name = "liftwizard-reladomo-serialize",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-jackson/liftwizard-jackson-config",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_jackson",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
