java_library(
    name = "liftwizard-bundle-logging-http",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-clock/liftwizard-config-clock",
        "//liftwizard-logging/liftwizard-config-logging-http",
        "//liftwizard-servlet/liftwizard-servlet-logging",
        "//liftwizard-servlet/liftwizard-servlet-logging-typesafe",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
