java_library(
    name = "liftwizard-bundle-connection-manager-holder",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-bundle/liftwizard-bundle-prioritized-api",
        "//liftwizard-config/liftwizard-config-data-source",
        "//liftwizard-reladomo/liftwizard-config-connection-manager",
        "//liftwizard-reladomo/liftwizard-connection-manager-holder",
        "@com_google_auto_service",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
