java_library(
    name = "liftwizard-config-logging-config",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-config/liftwizard-config-enabled",
    ],
)
