java_library(
    name = "liftwizard-logging-p6spy",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:net_logstash_logback_logstash_logback_encoder",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:p6spy_p6spy",
    ],
)
