#!/usr/bin/env bash

#MISE description="display available updates (dependencies, plugins, properties)"

#USAGE flag "--mvn_binary <mvn_binary>"  help="Maven binary to use"
#USAGE flag "--flags <flags>"            help="Additional Maven flags"

set -Eeuo pipefail

mvn_binary="${usage_mvn_binary:-${MVN_BINARY}}"
flags="${usage_flags:---threads 1}"

mise run maven --mvn_binary "${mvn_binary}" --target "versions:display-dependency-updates versions:display-plugin-updates versions:display-property-updates" --flags "${flags}" --profiles ""