#!/usr/bin/env bash

#MISE description="`mvn release:prepare`"
#MISE depends=["maven:clean","git:check-local-modifications"]
#MISE depends_post=["git:check-local-modifications"]

set -Eeuo pipefail

# Source the ansi colors
source .mise/tasks/console/ansi-colors

# Determine current and next version
CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

if [[ $CURRENT_VERSION =~ ([0-9]+)\.([0-9]+)\.([0-9]+)-SNAPSHOT ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    PATCH="${BASH_REMATCH[3]}"
    NEXT_VERSION="$MAJOR.$((MINOR + 1)).0-SNAPSHOT"
else
    NEXT_VERSION="$CURRENT_VERSION"
fi

echo "Current version is: ${ANSI_YELLOW}$CURRENT_VERSION${ANSI_DEFAULT}"

read -p "Enter next version (default: ${ANSI_YELLOW}$NEXT_VERSION${ANSI_DEFAULT}): " INPUT_VERSION
NEXT_VERSION=${INPUT_VERSION:-$NEXT_VERSION}

# Check out upstream branch
mise run console:run "git checkout ${ANSI_BRIGHT_RED}${ANSI_BOLD}${UPSTREAM_REMOTE}/${UPSTREAM_BRANCH}${ANSI_NORMAL}"

# Prepare the release
mise run console:run "mvn ${ANSI_MAGENTA}--batch-mode${ANSI_DEFAULT} clean release:clean release:prepare -DdevelopmentVersion=${ANSI_YELLOW}$NEXT_VERSION${ANSI_DEFAULT}"