#!/usr/bin/env bash

#MISE description="`mvn` rewrite"
#MISE depends_post=["git:check-local-modifications"]
#MISE depends=["maven:clean"]

#USAGE flag "--mvn_binary <mvn_binary>"  help="Maven binary to use"
#USAGE flag "--flags <flags>"            help="Additional Maven flags"

set -Eeuo pipefail

# Fallback to environment variables if flags aren't provided
mvn_binary="${usage_mvn_binary:-${MVN_BINARY}}"
flags="${usage_flags:-${MVN_FLAGS} -DskipTests}"

mise run maven --mvn_binary "$mvn_binary" --target "install org.openrewrite.maven:rewrite-maven-plugin:dryRun" --profiles "--activate-profiles rewrite-maven-plugin,rewrite-maven-plugin-dryRun" --flags "$flags"