#!/usr/bin/env bash

#MISE description="`mvn verify` with tests"
#MISE depends_post=["git:check-local-modifications"]
#MISE sources=["**/src/", "**/pom.xml"]
#MISE outputs=["**/target/surefire-reports/*.xml"]

#USAGE flag "--mvn_binary <mvn_binary>"  help="Maven binary to use" default="mvnd"

set -Eeuo pipefail

# Pass empty string for profiles
mise run maven --mvn_binary "$usage_mvn_binary" --target verify --profiles ""