java_library(
    name = "liftwizard-bundle-h2",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-bundle/liftwizard-bundle-prioritized-api",
        "//liftwizard-config/liftwizard-config-h2",
        "@com_google_auto_service",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_h2database_h2",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_lifecycle",
        "@maven//:janino_janino",
        "@maven//:javax_servlet_javax_servlet_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
