java_library(
    name = "liftwizard-config-metrics-reporter-logback",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-logging/liftwizard-config-metrics-reporter-slf4j",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:io_dropwizard_dropwizard_metrics",
        "@maven//:net_logstash_logback_logstash_logback_encoder",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
