java_library(
    name = "liftwizard-junit-rule-log-marker",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:junit_junit",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
