java_library(
    name = "liftwizard-config-logging-logzio",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_auto_service",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:ch_qos_logback_logback_core",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:io_dropwizard_dropwizard_logging",
        "@maven//:io_logz_logback_logzio_logback_appender",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
