java_library(
    name = "liftwizard-bundle-uuid",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-uuid/liftwizard-config-uuid",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:org_glassfish_hk2_hk2_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
