java_library(
    name = "liftwizard-jackson-config",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-jackson/liftwizard-jackson-pretty-printer",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_eclipse_collections",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
