java_library(
    name = "liftwizard-jackson-pretty-printer",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_google_code_findbugs_jsr305",
    ],
)
