java_library(
    name = "liftwizard-maven-reladomo-logger",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_goldmansachs_reladomo_reladomogen",
        "@maven//:janino_janino",
        "@maven//:org_apache_maven_maven_plugin_api",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
