java_library(
    name = "liftwizard-metrics-reporter-log4j",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:ch_qos_reload4j_reload4j",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
