java_library(
    name = "liftwizard-ansi-color-strip",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_fusesource_jansi_jansi",
    ],
)
