java_library(
    name = "liftwizard-graphql-operation-fetcher",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//liftwizard-graphql/liftwizard-graphql-exception",
        "//liftwizard-reladomo/liftwizard-reladomo-graphql-deep-fetcher",
        "//liftwizard-reladomo/liftwizard-reladomo-operation-compiler",
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_graphql_java_graphql_java",
        "@maven//:io_dropwizard_metrics_metrics_annotation",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
