set shell := ["bash", "-O", "globstar", "-c"]

# docs generate
generate:
    mvn package --projects docs --also-make --activate-profiles 'znai-maven-plugin'

# docs preview
preview:
    open http://localhost:3333/preview/
    mvn --threads 1 znai:preview --activate-profiles 'znai-maven-plugin'
