java_library(
    name = "liftwizard-task-reladomo-clear-cache",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_goldmansachs_reladomo_reladomo",
        "@maven//:com_google_guava_guava",
        "@maven//:io_dropwizard_dropwizard_servlets",
        "@maven//:janino_janino",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
