#!/usr/bin/env bash
#MISE description="Git rebase onto configurable upstream/main"
#MISE depends=["git:check-local-modifications", "git:fetch"]
#MISE raw=true

set -Eeuo pipefail

source .mise/tasks/console/ansi-colors

upstream_remote="${UPSTREAM_REMOTE:-upstream}"
upstream_branch="${UPSTREAM_BRANCH:-main}"

echo "git rebase --interactive --autosquash --rebase-merges --update-refs ${ANSI_BRIGHT_RED}${ANSI_BOLD}${upstream_remote}/${upstream_branch}${ANSI_NORMAL}"

git rebase --interactive --autosquash --rebase-merges --update-refs ${upstream_remote}/${upstream_branch}