java_library(
    name = "liftwizard-config-uuid",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_auto_service",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:io_dropwizard_dropwizard_jackson",
    ],
)
